"""add sub_category_id to products

Revision ID: 288530d81028
Revises: 8b4a7b2c1f2d
Create Date: 2026-06-16 11:07:32.245027
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288530d81028'
down_revision: Union[str, None] = '8b4a7b2c1f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sub_category_id', sa.UUID(), nullable=True))
    op.create_index('ix_products_sub_category_id', 'products', ['sub_category_id'], unique=False)
    op.create_foreign_key(None, 'products', 'categories', ['sub_category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index('ix_products_sub_category_id', table_name='products')
    op.drop_column('products', 'sub_category_id')
    # ### end Alembic commands ###
