"""add return fields to orders

Revision ID: ed164a1c7013
Revises: 12a340bd8581
Create Date: 2026-06-16 17:15:29.208843
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed164a1c7013'
down_revision: Union[str, None] = '12a340bd8581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_name='orders' AND column_name='return_reason'"
    ))
    if not result.fetchone():
        op.add_column('orders', sa.Column('return_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'return_reason')
    # ### end Alembic commands ###
