"""add is_active to discount_codes

Revision ID: f05a71183d88
Revises: f7f1360d023b
Create Date: 2026-06-12 15:24:25.737811
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f05a71183d88'
down_revision: Union[str, None] = 'f7f1360d023b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('test_enum_table_pg')
    op.add_column('discount_codes', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discount_codes', 'is_active')
    op.create_table('test_enum_table_pg',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='my_test_enum_pg'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('test_enum_table_pg_pkey'))
    )
    # ### end Alembic commands ###
