"""P1-02_initial_schema

Revision ID: f7f1360d023b
Revises: 
Create Date: 2026-06-11 10:51:47.611958
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7f1360d023b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create PostgreSQL enum types manually with checkfirst=True
    postgresql.ENUM('SUPER_ADMIN', 'ADMIN', 'VENDOR', 'RETAILER', name='user_role_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('ACTIVE', 'BLOCKED', 'PENDING', 'CREDIT_BLOCKED', 'DEACTIVATED', name='user_status_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('PENDING', 'CONFIRMED', 'DISPATCHED', 'DELIVERED', 'CANCELLED', name='order_status_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('INITIATED', 'SUCCESS', 'FAILED', 'REFUNDED', name='payment_status_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('ONLINE', 'CASH', 'CHEQUE', 'MANUAL', name='payment_method_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('ACTIVE', 'HIDDEN', name='product_status_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('FLAT', 'PERCENTAGE', name='discount_type_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('DEBIT', 'CREDIT', name='ledger_type_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('VOLUME', 'BUY_X_GET_Y', name='scheme_type_enum').create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('visible_to_vendor', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('visible_to_retailer', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_is_deleted'), 'categories', ['is_deleted'], unique=False)
    op.create_index('ix_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.create_index('ix_categories_slug', 'categories', ['slug'], unique=True, postgresql_where='is_deleted = false')
    op.create_table('discount_codes',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', postgresql.ENUM('FLAT', 'PERCENTAGE', name='discount_type_enum', create_type=False), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('min_order_value', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_usage_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_usage', sa.Integer(), server_default='0', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=True),
    sa.Column('scope_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discount_code', 'discount_codes', ['code'], unique=True, postgresql_where='is_deleted = false')
    op.create_index(op.f('ix_discount_codes_is_deleted'), 'discount_codes', ['is_deleted'], unique=False)
    op.create_table('users',
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('SUPER_ADMIN', 'ADMIN', 'VENDOR', 'RETAILER', name='user_role_enum', create_constraint=True, create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'BLOCKED', 'PENDING', 'CREDIT_BLOCKED', 'DEACTIVATED', name='user_status_enum', create_type=False), server_default='ACTIVE', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('geo_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True, postgresql_where='is_deleted = false AND email IS NOT NULL')
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index('ix_users_mobile', 'users', ['mobile'], unique=True, postgresql_where='is_deleted = false')
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('audit_log',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('diff_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor_id', 'audit_log', ['actor_id'], unique=False)
    op.create_index('ix_audit_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_is_deleted'), 'audit_log', ['is_deleted'], unique=False)
    op.create_table('carts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_is_deleted'), 'carts', ['is_deleted'], unique=False)
    op.create_index('ix_carts_user_id', 'carts', ['user_id'], unique=True, postgresql_where='is_deleted = false')
    op.create_table('device_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_tokens_is_deleted'), 'device_tokens', ['is_deleted'], unique=False)
    op.create_index('ix_device_tokens_user_id', 'device_tokens', ['user_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', postgresql.ENUM('DEBIT', 'CREDIT', name='ledger_type_enum', create_type=False), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_created_at', 'ledger_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_ledger_entries_is_deleted'), 'ledger_entries', ['is_deleted'], unique=False)
    op.create_index('ix_ledger_user_id', 'ledger_entries', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('delivery_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'CONFIRMED', 'DISPATCHED', 'DELIVERED', 'CANCELLED', name='order_status_enum', create_type=False), server_default='PENDING', nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('gst_amount', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Integer(), nullable=False),
    sa.Column('grand_total', sa.Integer(), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('discount_code_id', sa.UUID(), nullable=True),
    sa.Column('voice_order', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('voice_clip_url', sa.Text(), nullable=True),
    sa.Column('eway_bill_no', sa.String(length=50), nullable=True),
    sa.Column('eway_bill_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['discount_code_id'], ['discount_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index(op.f('ix_orders_is_deleted'), 'orders', ['is_deleted'], unique=False)
    op.create_index('ix_orders_order_number', 'orders', ['order_number'], unique=True)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_table('otps',
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('otp_hash', sa.Text(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_is_deleted'), 'otps', ['is_deleted'], unique=False)
    op.create_index('ix_otps_mobile', 'otps', ['mobile'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.Column('gst_rate', sa.Integer(), server_default='18', nullable=False),
    sa.Column('stock_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), server_default='10', nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'HIDDEN', name='product_status_enum', create_type=False), server_default='ACTIVE', nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_is_deleted'), 'products', ['is_deleted'], unique=False)
    op.create_index('ix_products_search', 'products', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_products_sku', 'products', ['sku'], unique=True, postgresql_where='is_deleted = false')
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_is_deleted'), 'refresh_tokens', ['is_deleted'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('retailers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('credit_limit', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_retailers_is_deleted'), 'retailers', ['is_deleted'], unique=False)
    op.create_table('vendors',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('pan_number', sa.String(length=15), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_vendors_is_deleted'), 'vendors', ['is_deleted'], unique=False)
    op.create_table('cart_items',
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_snapshot', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cart_items_cart_product', 'cart_items', ['cart_id', 'product_id'], unique=True, postgresql_where='is_deleted = false')
    op.create_index(op.f('ix_cart_items_is_deleted'), 'cart_items', ['is_deleted'], unique=False)
    op.create_table('dealer_pricing',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_pricing_is_deleted'), 'dealer_pricing', ['is_deleted'], unique=False)
    op.create_index('ix_dealer_pricing_product_user', 'dealer_pricing', ['product_id', 'user_id'], unique=True, postgresql_where='is_deleted = false')
    op.create_table('dealer_schemes',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('scheme_type', postgresql.ENUM('VOLUME', 'BUY_X_GET_Y', name='scheme_type_enum', create_type=False), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('min_qty', sa.Integer(), nullable=False),
    sa.Column('discount_pct', sa.Integer(), nullable=False),
    sa.Column('free_qty', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_schemes_is_deleted'), 'dealer_schemes', ['is_deleted'], unique=False)
    op.create_index('ix_dealer_schemes_user_id', 'dealer_schemes', ['user_id'], unique=False)
    op.create_table('invoices',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('buyer_gstin', sa.String(length=20), nullable=True),
    sa.Column('seller_gstin', sa.String(length=20), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('cgst', sa.Integer(), nullable=False),
    sa.Column('sgst', sa.Integer(), nullable=False),
    sa.Column('igst', sa.Integer(), nullable=False),
    sa.Column('grand_total', sa.Integer(), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_invoices_is_deleted'), 'invoices', ['is_deleted'], unique=False)
    op.create_index('ix_invoices_number', 'invoices', ['invoice_number'], unique=True)
    op.create_index('ix_invoices_order_id', 'invoices', ['order_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('gst_rate', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Integer(), nullable=False),
    sa.Column('gst_amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_is_deleted'), 'order_items', ['is_deleted'], unique=False)
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('INITIATED', 'SUCCESS', 'FAILED', 'REFUNDED', name='payment_status_enum', create_type=False), server_default='INITIATED', nullable=False),
    sa.Column('method', postgresql.ENUM('ONLINE', 'CASH', 'CHEQUE', 'MANUAL', name='payment_method_enum', create_type=False), nullable=False),
    sa.Column('gateway_order_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_signature', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_is_deleted'), 'payments', ['is_deleted'], unique=False)
    op.create_index('ix_payments_order_id', 'payments', ['order_id'], unique=False)
    op.create_index('ix_payments_user_id', 'payments', ['user_id'], unique=False)
    op.create_table('product_images',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_is_deleted'), 'product_images', ['is_deleted'], unique=False)
    op.create_index('ix_product_images_product_id', 'product_images', ['product_id'], unique=False)
    op.create_table('retailer_pricing',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_pricing_is_deleted'), 'retailer_pricing', ['is_deleted'], unique=False)
    op.create_index('ix_retailer_pricing_product', 'retailer_pricing', ['product_id'], unique=True, postgresql_where='is_deleted = false')
    op.create_table('vendor_pricing',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_pricing_is_deleted'), 'vendor_pricing', ['is_deleted'], unique=False)
    op.create_index('ix_vendor_pricing_product', 'vendor_pricing', ['product_id'], unique=True, postgresql_where='is_deleted = false')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vendor_pricing_product', table_name='vendor_pricing', postgresql_where='is_deleted = false')
    op.drop_index(op.f('ix_vendor_pricing_is_deleted'), table_name='vendor_pricing')
    op.drop_table('vendor_pricing')
    op.drop_index('ix_retailer_pricing_product', table_name='retailer_pricing', postgresql_where='is_deleted = false')
    op.drop_index(op.f('ix_retailer_pricing_is_deleted'), table_name='retailer_pricing')
    op.drop_table('retailer_pricing')
    op.drop_index('ix_product_images_product_id', table_name='product_images')
    op.drop_index(op.f('ix_product_images_is_deleted'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('ix_payments_user_id', table_name='payments')
    op.drop_index('ix_payments_order_id', table_name='payments')
    op.drop_index(op.f('ix_payments_is_deleted'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_index(op.f('ix_order_items_is_deleted'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_invoices_order_id', table_name='invoices')
    op.drop_index('ix_invoices_number', table_name='invoices')
    op.drop_index(op.f('ix_invoices_is_deleted'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_dealer_schemes_user_id', table_name='dealer_schemes')
    op.drop_index(op.f('ix_dealer_schemes_is_deleted'), table_name='dealer_schemes')
    op.drop_table('dealer_schemes')
    op.drop_index('ix_dealer_pricing_product_user', table_name='dealer_pricing', postgresql_where='is_deleted = false')
    op.drop_index(op.f('ix_dealer_pricing_is_deleted'), table_name='dealer_pricing')
    op.drop_table('dealer_pricing')
    op.drop_index(op.f('ix_cart_items_is_deleted'), table_name='cart_items')
    op.drop_index('ix_cart_items_cart_product', table_name='cart_items', postgresql_where='is_deleted = false')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_vendors_is_deleted'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_retailers_is_deleted'), table_name='retailers')
    op.drop_table('retailers')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_deleted'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_products_sku', table_name='products', postgresql_where='is_deleted = false')
    op.drop_index('ix_products_search', table_name='products', postgresql_using='gin')
    op.drop_index(op.f('ix_products_is_deleted'), table_name='products')
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_otps_mobile', table_name='otps')
    op.drop_index(op.f('ix_otps_is_deleted'), table_name='otps')
    op.drop_table('otps')
    op.drop_index('ix_orders_user_id', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_order_number', table_name='orders')
    op.drop_index(op.f('ix_orders_is_deleted'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_ledger_user_id', table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_is_deleted'), table_name='ledger_entries')
    op.drop_index('ix_ledger_created_at', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_device_tokens_user_id', table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_is_deleted'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index('ix_carts_user_id', table_name='carts', postgresql_where='is_deleted = false')
    op.drop_index(op.f('ix_carts_is_deleted'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_audit_log_is_deleted'), table_name='audit_log')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_index('ix_audit_created_at', table_name='audit_log')
    op.drop_index('ix_audit_actor_id', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_mobile', table_name='users', postgresql_where='is_deleted = false')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index('ix_users_email', table_name='users', postgresql_where='is_deleted = false AND email IS NOT NULL')
    op.drop_table('users')
    op.drop_index(op.f('ix_discount_codes_is_deleted'), table_name='discount_codes')
    op.drop_index('ix_discount_code', table_name='discount_codes', postgresql_where='is_deleted = false')
    op.drop_table('discount_codes')
    op.drop_index('ix_categories_slug', table_name='categories', postgresql_where='is_deleted = false')
    op.drop_index('ix_categories_parent_id', table_name='categories')
    op.drop_index(op.f('ix_categories_is_deleted'), table_name='categories')
    op.drop_table('categories')
    # Drop all custom enum types manually with checkfirst=True
    postgresql.ENUM('SUPER_ADMIN', 'ADMIN', 'VENDOR', 'RETAILER', name='user_role_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM('ACTIVE', 'BLOCKED', 'PENDING', 'CREDIT_BLOCKED', 'DEACTIVATED', name='user_status_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM('PENDING', 'CONFIRMED', 'DISPATCHED', 'DELIVERED', 'CANCELLED', name='order_status_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM('INITIATED', 'SUCCESS', 'FAILED', 'REFUNDED', name='payment_status_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM('ONLINE', 'CASH', 'CHEQUE', 'MANUAL', name='payment_method_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM('ACTIVE', 'HIDDEN', name='product_status_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM('FLAT', 'PERCENTAGE', name='discount_type_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM('DEBIT', 'CREDIT', name='ledger_type_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM('VOLUME', 'BUY_X_GET_Y', name='scheme_type_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
